name: myeachtra
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pip
  - setuptools
  - ipykernel
  - pandas
  - pytorch==2.2.1
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - pytorch-cuda=11.8
  - nvidia::cuda=11.8
  - pip:
    - transformers==4.40.0
    - timm==0.4.12
    - sentencepiece
    - gradio==4.13.0
    - markdown2==2.4.10
    - xlsxwriter==3.1.2
    - einops
    - ftfy
    - regex
    - tqdm
    - git+https://github.com/openai/CLIP.git
    - commentjson==0.9.0
    - dateparser==1.1.8
    - elastic_transport==8.13.0
    - fastapi
    - holidays==0.45
    - nltk
    - numpy
    - open_clip_torch==2.24.0
    - openai==1.26.0
    - pandas==1.5.3
    - parsedatetime==2.6
    - partialjson==0.0.5
    - Pillow==10.3.0
    - pydantic==2.7.1
    - pymongo==4.6.1
    - pytest==8.1.1
    - python-dotenv==1.0.1
    - python_hostlist==1.23.0
    - pytimeparse==1.1.8
    - redis==5.0.3
    - rest_framework_simplejwt==0.0.2
    - rich==13.7.1
    - scikit_learn==1.3.2
    - elasticsearch
    - jsonlines
    - async_timeout
    - pyright
    - pycln
    - isort
    - black
    - rope


